export const airports = [
    { id: "ATL", label: "Atlanta (ATL)" },
    { id: "PEK", label: "Beijing (PEK)" },
    { id: "LHR", label: "London (LHR)" },
    { id: "ORD", label: "Chicago (ORD)" },
    { id: "HND", label: "Tokyo (HND)" },
    { id: "LAX", label: "Los Angeles (LAX)" },
    { id: "CDG", label: "Paris (CDG)" },
    { id: "DFW", label: "Dallas (DFW)" },
    { id: "FRA", label: "Frankfurt (FRA)" },
    { id: "HKG", label: "Hong Kong (HKG)" },
    { id: "DEN", label: "Denver (DEN)" },
    { id: "DXB", label: "Dubai (DXB)" },
    { id: "CGK", label: "Jakarta (CGK)" },
    { id: "AMS", label: "Amsterdam (AMS)" },
    { id: "COL", label: "Colombo (COL)" },
    { id: "MAD", label: "Madrid (MAD)" },
    { id: "BKK", label: "Bangkok (BKK)" },
    { id: "JFK", label: "New York (JFK)" },
    { id: "SIN", label: "Singapore (SIN)" },
    { id: "CAN", label: "Guangzhou (CAN)" },
    { id: "LAS", label: "Las Vegas (LAS)" },
    { id: "PVG", label: "Shanghai (PVG)" },
    { id: "SFO", label: "San Francisco (SFO)" },
    { id: "PHX", label: "Phoenix (PHX)" },
    { id: "IAH", label: "Houston (IAH)" },
    { id: "CLT", label: "Charlotte (CLT)" },
    { id: "MIA", label: "Miami (MIA)" },
    { id: "MUC", label: "Munich (MUC)" },
    { id: "KUL", label: "Kuala Lumpur (KUL)" },
    { id: "FCO", label: "Rome (FCO)" },
    { id: "IST", label: "Istanbul (IST)" },
    { id: "SYD", label: "Sydney (SYD)" },
    { id: "MCO", label: "Orlando (MCO)" },
    { id: "ICN", label: "Seoul (ICN)" },
    { id: "DEL", label: "Delhi (DEL)" },
    { id: "BCN", label: "Barcelona (BCN)" },
    { id: "LGW", label: "London (LGW)" },
    { id: "EWR", label: "Newark (EWR)" },
    { id: "YYZ", label: "Toronto (YYZ)" },
    { id: "SHA", label: "Shanghai (SHA)" },
    { id: "MSP", label: "Minneapolis (MSP)" },
    { id: "SEA", label: "Seattle (SEA)" },
    { id: "DTW", label: "Detroit (DTW)" },
    { id: "PHL", label: "Philadelphia (PHL)" },
    { id: "BOM", label: "Mumbai (BOM)" },
    { id: "GRU", label: "Sao Paulo (GRU)" },
    { id: "MNL", label: "Manila (MNL)" },
    { id: "CTU", label: "Chengdu (CTU)" },
    { id: "BOS", label: "Boston (BOS)" },
    { id: "SZX", label: "Shenzhen (SZX)" },
    { id: "MEL", label: "Melbourne (MEL)" },
    { id: "NRT", label: "Tokyo (NRT)" },
    { id: "ORY", label: "Paris (ORY)" },
    { id: "MEX", label: "Mexico City (MEX)" },
    { id: "DME", label: "Moscow (DME)" },
    { id: "AYT", label: "Antalya (AYT)" },
    { id: "TPE", label: "Taipei (TPE)" },
    { id: "ZRH", label: "Zurich (ZRH)" },
    { id: "LGA", label: "New York (LGA)" },
    { id: "FLL", label: "Fort Lauderdale (FLL)" },
    { id: "IAD", label: "Washington (IAD)" },
    { id: "PMI", label: "Palma Mallorca (PMI)" },
    { id: "CPH", label: "Copenhagen (CPH)" },
    { id: "SVO", label: "Moscow (SVO)" },
    { id: "BWI", label: "Baltimore (BWI)" },
    { id: "KMG", label: "Kunming (KMG)" },
    { id: "VIE", label: "Vienna (VIE)" },
    { id: "OSL", label: "Oslo (OSL)" },
    { id: "JED", label: "Jeddah (JED)" },
    { id: "BNE", label: "Brisbane (BNE)" },
    { id: "SLC", label: "Salt Lake City (SLC)" },
    { id: "DUS", label: "Dusseldorf (DUS)" },
    { id: "BOG", label: "Bogota (BOG)" },
    { id: "MXP", label: "Milan (MXP)" },
    { id: "JNB", label: "Johannesburg (JNB)" },
    { id: "ARN", label: "Stockholm (ARN)" },
    { id: "MAN", label: "Manchester (MAN)" },
    { id: "MDW", label: "Chicago (MDW)" },
    { id: "DCA", label: "Washington (DCA)" },
    { id: "BRU", label: "Brussels (BRU)" },
    { id: "DUB", label: "Dublin (DUB)" },
    { id: "GMP", label: "Seoul (GMP)" },
    { id: "DOH", label: "Doha (DOH)" },
    { id: "STN", label: "London (STN)" },
    { id: "HGH", label: "Hangzhou (HGH)" },
    { id: "CJU", label: "Jeju (CJU)" },
    { id: "YVR", label: "Vancouver (YVR)" },
    { id: "TXL", label: "Berlin (TXL)" },
    { id: "SAN", label: "San Diego (SAN)" },
    { id: "TPA", label: "Tampa (TPA)" },
    { id: "CGH", label: "Sao Paulo (CGH)" },
    { id: "BSB", label: "Brasilia (BSB)" },
    { id: "CTS", label: "Sapporo (CTS)" },
    { id: "XMN", label: "Xiamen (XMN)" },
    { id: "RUH", label: "Riyadh (RUH)" },
    { id: "FUK", label: "Fukuoka (FUK)" },
    { id: "GIG", label: "Rio De Janeiro (GIG)" },
    { id: "HEL", label: "Helsinki (HEL)" },
    { id: "LIS", label: "Lisbon (LIS)" },
    { id: "ATH", label: "Athens (ATH)" },
    { id: "AKL", label: "Auckland (AKL)" },

]

export const topDestinations = [
    { id: 1, city: "Singapore", img: "https://res.klook.com/image/upload/cities/jv8g79dw3j5fmi9qozoa.jpg" },
    { id: 2, city: "Tokyo", img: "https://res.klook.com/image/upload/cities/xvp6saafvo0aeykw3di0.jpg" },
    { id: 3, city: "Bangkok", img: "https://res.klook.com/image/upload/cities/wbulbfghbwsuvelgvibn.jpg" },
    { id: 4, city: "London", img: "https://res.klook.com/image/upload/cities/xkeic9zojhtxffeovjtl.jpg" },
    { id: 5, city: "Paris", img: "https://res.klook.com/image/upload/cities/bqi3forinxbwjuknp04v.jpg" },
    { id: 6, city: "New York", img: "https://res.klook.com/image/upload/cities/liw377az16sxmp9a6ylg.jpg" },
    { id: 7, city: "Rome", img: "https://www.planetware.com/wpimages/2020/08/top-attractions-in-the-world-italy-rome-colosseum.jpg" },
    { id: 8, city: "Grand Canyon", img: "https://www.planetware.com/wpimages/2020/08/top-attractions-in-the-world-arizona-grand-canyon.jpg" },
    { id: 1, city: "Cairo", img: "https://www.planetware.com/wpimages/2020/08/top-attractions-in-the-world-egypt-pyramids-giza.jpg" },
]